# .github/labeler.yml

# Labels for specific modules
app:
  - 'src/app/**/*'

common:
  - 'src/common/**/*'

config:
  - 'src/config/**/*'

decorators:
  - 'src/decorators/**/*'

exceptions:
  - 'src/exceptions/**/*'

filters:
  - 'src/filters/**/*'

interceptors:
  - 'src/interceptors/**/*'

main:
  - 'src/main.ts'

migrations:
  - 'src/migrations/**/*'

auth-module:
  - 'src/modules/auth/**/*'

bank-module:
  - 'src/modules/bank/**/*'

user-module:
  - 'src/modules/user/**/*'

# Labels for template-related files
template-module:
  - 'template_module/**/*'

# Labels for test files
tests:
  - 'test/**/*'

# Labels for configuration files
tsconfig:
  - 'tsconfig.json'
  - 'tsconfig.build.json'

# Catch-all for other changes
miscellaneous:
  - '**/*'
