services:
  main:
    image: ${COMPOSE_PROJECT_NAME}/main:20-alpine
    build:
      context: .
    command: >
      /bin/sh -c "npm install &&
                  npm run build &&
                  npm run typeorm:migration:run &&
                  npm run start:debug"
    restart: on-failure
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/var/www
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${PG_DATABASE}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - ./multi_pg_databases:/docker-entrypoint-initdb.d
      - banking_postgres:/var/lib/postgresql/data

volumes:
  banking_postgres:
