services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - ./multi_pg_databases:/docker-entrypoint-initdb.d
      - banking_postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # command: redis-server --requirepass redis
volumes:
  banking_postgres:
  redis_data:
