services:
  main:
    image: ${APP_NAME}/main:18-alpine
    build:
      context: .
    command: >
      /bin/sh -c "npm install &&
                  npm run build &&
                  npm run typeorm:migration:run &&
                  npm run start:debug"
    restart: on-failure
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/var/www
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - ./multi_pg_databases:/docker-entrypoint-initdb.d
      - banking_postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command:
      [
        'redis-server',
        '--requirepass',
        '${REDIS_PASSWORD}',
        '--save',
        '60 1',
        '--loglevel',
        'warning',
      ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
volumes:
  banking_postgres:
  redis_data:
