services:
  main:
    image: nhbank/main:18-alpine
    build:
      context: .
    command: >
      /bin/sh -c "npm install &&
                  npm run build &&
                  npm run migration:run &&
                  npm run start:dev"
    restart: on-failure
    volumes:
      - ./:/var/www
    ports:
      - '${APP_PORT}:80'
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${PG_DATABASE}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - ./multi_pg_databases:/docker-entrypoint-initdb.d
      - banking_postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  banking_postgres:
  redis_data:
