services:
  postgres:
    image: postgres:alpine
    container_name: banking_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: banking_backend
    ports:
      - '5400:5432'
    volumes:
      - ./multi_pg_databases:/docker-entrypoint-initdb.d
      - baking_postgres:/var/lib/postgresql/data

volumes:
  baking_postgres:
