services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: buddyus
    ports:
      - '5432:5432'
    volumes:
      - ./multi_pg_databases:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
